### Base URL
@baseUrl = http://localhost:3000

### =============================================
### POSTS API ENDPOINTS
### =============================================

### CREATE a new post
POST {{baseUrl}}/posts
Content-Type: application/json

{
  "title": "strawberry cake",
  "publisher": "Hadar Lachmy",
  "content": "I'm looking for a good recipe for strawberry cake."
}

### GET all posts
GET {{baseUrl}}/posts
Content-Type: application/json

### GET posts by sender
GET {{baseUrl}}/posts?sender=Hadar Lachmy
Content-Type: application/json

### GET post by ID
GET {{baseUrl}}/posts/697a63f33abc75f1bfe568ca
Content-Type: application/json

### UPDATE a post
PUT {{baseUrl}}/posts/697a63f33abc75f1bfe568ca
Content-Type: application/json

{
  "title": "Updated strawberry cake",
  "publisher": "Hadar Lachmy",
  "content": "Updated recipe for strawberry cake."
}


### Get Comment By Post ID

GET http://localhost:3000/comments/?postId=673c88b56b1c980fce4558b0

### Get Comment By ID (Does not exist)

GET http://localhost:3000/comments/673ca4bcfb3be23fb7217851

### Get Comment By ID

GET http://localhost:3000/comments/673ca4bcfb3be23fb7217852

### Create Comment

POST http://localhost:3000/comments content-type: application/json

{
	"postId": "673c88b56b1c980fce4558b0",
	"sender": "Tal eyal",
	"content": "i am looking for pets."
}

### Update comment's sender

PUT http://localhost:3000/comments/673ca4bcfb3be23fb3217852 content-type: application/json

{
"sender": "tal"
}

### Update comment's content

PUT http://localhost:3000/posts/674ca4bcfb3be23fb7217852 content-type: application/json

{
"content": "looking for recipe"
}

### Delete Comment By ID

DELETE http://localhost:3000/comments/674ca4bcfb3be23fb7217852
